### PR TITLE
Update to 1.21.1

### PR DESCRIPTION
**Pull request by llakala**
I needed this mod for 1.21.1, so I updated it for myself! Working great on my machine, but if you want any changes, feel free to request them.

### CODE REVIEW

**Comment by NerjalNosk** [comment]
Lmfao gotta love how it just works, meaning Mojang didn't change anything to chunk saving since then

**Comment by NerjalNosk** [comment]
I will look into it soon, most likely will merge, albeit with a few minor changes to make it support most game versions at once, yet without breaking for oldest ones because compiled with a too recent version of Java.

**Comment by llakala** [comment]
> Lmfao gotta love how it just works, meaning Mojang didn't change anything to chunk saving since then

And we love that! @/mojang, no making breaking changes, I need easy mod updates.

**Comment by NerjalNosk** [comment]
Now published on [Modrinth](https://modrinth.com/mod/structure-remover/version/1.1.0+mc1.20.1)

**Pull request merged**
